[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message-io = "0.14"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"